services:
  db:
    image: postgres:alpine  
    container_name: db-service
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro  
    ports:
      - "5432:5432" 
    env_file:
      - ./db/.env
    networks:
      - app-net
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U user -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  web-app:
      build: ./web-app
      container_name: web-app-service  
      depends_on:  
        - db
      env_file:
      - ./web-app/.env      
      ports:
        - "3000:3000"
      networks:
        - app-net
      mem_limit: 64m  

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  
    depends_on:
      - web-app
    networks:
      - app-net

networks:
  app-net:
    driver: bridge  
    ipam:
      config:
        - subnet: 192.168.0.0/16  

volumes:
  db-data:  